### ISSUE TITLE
Iteration 1 ToDo List

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/vscode-azure-agent#1]
# Iteration 1
Goals:
- Make it possible for all `@azure-functions` agent functionality to work again (re-implement at least one actionable functionality to prove the efforts work)
- Do so in a way that is scalable & non-disruptive to the Azure Extensions for VS Code
- Enable easy to use integration with the Azure Extensions for VS Code

## Meta Tasks
   - [x] CI/CD
   - [x] README
   - [x] Extension Display Properties
      - [x] Name
      - [x] Logo
      - [x] Description

## Actionable prompts
   - [x] Get Service Extension Integration to the point other folks can work on it
      - [x] Open [azure-tools PR](https://github.com/microsoft/vscode-azuretools/pull/1680) to team review
      - [x] Generalize the code for an extension level slash command
      - [x] Code for handling extensions not installed
      - [x] Scalable commands support
         - [x] ~~Prototype schema API idea~~ Not using, move to wizard based extension schema
         - [x] Wizard based extension schema idea
         - [x] Hook up wizard based extension schema to a service extension
            - [x] Open initial prototype PRs
               - [x] [Azure Functions](https://github.com/microsoft/vscode-azurefunctions/pull/3941)
               - [x] ~~[Azure Agent](https://github.com/microsoft/vscode-azure-agent/pull/24)~~
            - [x] Problems found during initial prototype that need solving:
               - [x] Service Extension Side:
                  - [x] How to get existing wizard steps to use the agent related `IAzureUserInput` types?
                  - [x] What will happen if Agent figures everything? Do we need to make sure the wizard is being executed as a "dry run"?
               - [x] Agent Extension Side:                        
                  - [x] Commands definitely need high quality intent descriptions, need to help rest of team with examples
                  - [x] Need to make sure we have a good handle on stripping icons from srings
                  - [x] During `IAzureUserInput` methods, the agent needs to be told, in a consistent way, what parameter it is trying to solve, both for purposes of the "solve parameter" system prompt, and for later when invoking the command
                  - [x] Prototype does not currently implement `activate()`
                  - [x] Some pick items are "fake", ex: "Some stacks have an end of support deadline coming up. Learn more...", service extension maye need to communicate which items are like that.

## Informational prompts
   - [x] De-dupe code for brainstorm and learn commands
   - [x] Implement Microsoft Learn RAG
   - [x] Support "What can the agent do?" prompts

## Follow-ups
   - [x] Informational follow-ups
      - [x] Bring back what was present in Azure Functions agent experiment
   - [x] Actionaable follow-ups
      - [x] Bring back what was present in Azure Functions agent experiment

## Benchmarking
   - [x] Implement basic benchmarking
   - [x] Add benchmarking to external types
