### ISSUE TITLE
Iteration 2 ToDo List

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/vscode-azure-agent#45]
# Iteration 2
Goals:
- Have at least one other Azure extension dev expose an existing Azure Extension functionality via actionable prompts, and then get more folks expsoing features after that.
- Refine and polish experiences
- Figure out conversating.
- Ensure RAG quality.

## Meta Tasks
- [x] Ensure experience is good when no top level command is matched, including with RAG
- [x] Get [Architecture Doc](https://github.com/microsoft/vscode-azure-agent/pull/38) merged
- [x] 1ES Pipeline work
- [ ] High level guide on exposing functionality to the agent
- [ ] Explore adverserial prompts and guardrails against them more
- [ ] Reach out to security experts regarding client identity secrets

## Actionable prompts
- [ ] Service Extensions Side:
   - [x] Get azure-tools [PR](https://github.com/microsoft/vscode-azuretools/pull/1680) closed
   - [x] Get example Azure Functions [PR](https://github.com/microsoft/vscode-azurefunctions/pull/3941) reviewed and closed
   - [ ] Determine prioritization of exposing existing Azure Extension functionality via actionable prompts
   - [ ] What happens if a determined parameter fails validation?
- [ ] Agent Extension Side:
   - [ ] What limits exist for the agent handling picking from many things? Do we need to split big decisions up?
   - [ ] The agent's picked value is not always exact, probably need to do something a bit more relaxed than exact match.
   - [ ] See if new types allow for multiple buttons/rendering buttons not at bottom.
   - [ ] Get workspace context, such as language
   - [ ] Agent is eager to suggest text input, is that ok? Suggestions are often invalid, how can we improve this?
   - [x] Make use of history (user changing determined information, user providing needed information)
   - [x] Get slash commands for all existing Azure Extensions for VS Code
- [ ] Handle commands requiring specific prerequisites:
   - [ ] Sign-in
   - [ ] Open workspace           

## Informational prompts
   - [ ] Read through Microsoft Learn RAG docs, make sure we are grabbing full content of returned docs
   - [ ] Have learn prompt instruct LLM to explain conceptual translations
   - [ ] Clean up system prompt to make it clear user is in VS code and if they do/don't have extensions installed
   - [ ] Get workspace context, such as language
   - [x] Make use of history
   - [x] Discuss getting rid of brainstorm
   - [x] Get rid of brainstorm and simplify common commands
   - [x] Suggest installing extension associated with informational prompt

## Follow-ups
   - [ ] Informational follow-ups
      - [ ] ???
   - [ ] Actionable follow-ups
      - [ ] Improve quality
      - [ ] Figure out giving them in a natual sentence structure

## Benchmarking
   - [x] Add some agent benchmarks
   - [x] Make it easy to run all benchmarks
   - [ ] Run benchmarks from an extension

## Feedback/Telemetry
   - [ ] Implement telemetry
      - [ ] When feedback is received (user like/not like?)
      - [ ] When agent is done responding (how did it respond?)

## Prior Iterations
- Iteration 1: https://github.com/microsoft/vscode-azure-agent/issues/1

**Comment by MRayermannMSFT** [comment]
Closing iteration. All not-completed items are currently cut until further notice.
